### ISSUE TITLE
Add YAML config for ftdi_gpio

### ISSUE THREAD

**Issue by superna9999** [linux-msm/cdba#42]
As of today, a single string configures the FTDI gpios.

Switch from:
```
    ftdi_gpio: "s:0xVEND:0xPROD:SERIAL;D;POWER,0,ACTIVE_LOW;FASTBOOT_KEY,1,ACTIVE_HIGH;POWER_KEY,2,ACTIVE_HIGH;USB_DISCONNECT,3,ACTIVE_LOW"
```

to 

```
    ftdi_gpio:
     description: "s:0xVEND:0xPROD:SERIAL"
     interface: D
     gpios:
        - power:
            line: 0
            active_low: true
        - fastboot_key:
            line: 1
        - power_key:
            line: 2
        - usb_disconnect:
            line: 3
            active_low: true
```

but still accept the previous format with a warning

**Comment by superna9999** [comment]
I think "interface" should go under each gpio so we can use gpios from all the interfaces, but it would need some code change

**Comment by superna9999** [comment]
And I could move description to:
```
    ftdi_gpio:
     vendor: 0xVEND
     product: 0xPROD
     serial: SERIAL
     index: 0
     devicenode: /dev/bus/usb/....
```

and depending of the provided variable, construct the libftdi init string accordingly:
```
d:<devicenode>
i:<vendor>:<product>
i:<vendor>:<product>:<index>
s:<vendor>:<product>:<serial>
```
